### ISSUE TITLE
DirContainsRegex takes too long

### ISSUE THREAD

**Issue by KaliPatriot** [sourque/aeacus#100]
Doing DirContainsRegex in a directory may take a long time to execute if there are large binaries within. Consider checking file size before attempting the regex OR checking if the file is not a binary

**Comment by safinsingh** [comment]
It really shouldn't be _that_ slow. 

We're already imposing a limit on recursion and this seems like a really uncommon edge case. If you're experiencing serious performance issues, feel free to edit and re-compile `aeacus` as needed.

**Comment by safinsingh** [comment]
The firefox check was removed in 59347ad24ee29a9e8b21998c5f20c085445bd736 due to reliability concerns.
