### ISSUE TITLE
How to score if Smart Screen is turned on

### ISSUE THREAD

**Issue by ShadowSchulme** [sourque/aeacus#126]
I was looking at the list of commands for scoring and I was unsure of how best to score whether smart screen is turned on. I think it is possible to score through the registry but I think that requires editing and creating keys beforehand. Smart screen if enabled or disabled through the windows settings menu does not make, change or create the keys in my image. I know that these settings can be changed through group policy and that would be my preferred way to teach it and score it. Im just not sure what the best way to do this is.  - Thanks for your time

**Comment by Altoid0** [comment]
Hey there,
Apologies for the last response but hopefully this answers your question.

I would score Smartscreen like this to account for GPO/Registry methods as well as enabling the setting through Windows Security (GUI). passoverride allows us to made OR conditions which makes it so the check passes if SmartScreen is enabled through the standard GUI windows or a Group Policy:
```toml
[[check]]
message = "Windows Defender SmartScreen Enabled"
points = X

[[check.passoverride]]
type = "RegistryKeyNot"
arg1 = 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\SmartScreenEnable'
arg2 = "Off"
[[check.passoverride]]
type = "RegistryKey"
arg1 = 'HKLM\SOFTWARE\Policies\Microsoft\Windows\System\EnableSmartScreen'
arg2 = "1"
[[check.passoverride]]
type = "RegistryKey"
arg1 = 'HKLM\SOFTWARE\Policies\Microsoft\Windows\System\EnableSmartScreen'
arg2 = "2"

**Comment by ShadowSchulme** [comment]
Awesome thanks!  I am also not sure how to score remote desktop. Any tips or should I put in another request? From: Altoid0Sent: Saturday, September 4, 2021 5:47 PMTo: elysium-suite/aeacusCc: ShadowSchulme; AuthorSubject: Re: [elysium-suite/aeacus] How to score if Smart Screen is turned on (#126) Hey there,Apologies for the last response but hopefully this answers your question.I would score Smartscreen like this to account for GPO/Registry methods as well as enabling the setting through Windows Security (GUI). passoverride allows us to made OR conditions which makes it so the check passes if SmartScreen is enabled through the standard GUI windows or a Group Policy:[[check]]message = "Windows Defender SmartScreen Enabled"points = X [[check.passoverride]]type = "RegistryKeyNot"arg1 = "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\SmartScreenEnable"arg2 = "Off"[[check.passoverride]]type = "RegistryKey"arg1 = "HKLM\SOFTWARE\Policies\Microsoft\Windows\SystemEnableSmartScreen"arg2 = "1"[[check.passoverride]]type = "RegistryKey"arg1 = "HKLM\SOFTWARE\Policies\Microsoft\Windows\SystemEnableSmartScreen"arg2 = "2"—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ShadowSchulme** [comment]
Nevermind to the remote desktop question I found the closed issue where you answered the question Thanks! From: Altoid0Sent: Saturday, September 4, 2021 5:47 PMTo: elysium-suite/aeacusCc: ShadowSchulme; AuthorSubject: Re: [elysium-suite/aeacus] How to score if Smart Screen is turned on (#126) Hey there,Apologies for the last response but hopefully this answers your question.I would score Smartscreen like this to account for GPO/Registry methods as well as enabling the setting through Windows Security (GUI). passoverride allows us to made OR conditions which makes it so the check passes if SmartScreen is enabled through the standard GUI windows or a Group Policy:[[check]]message = "Windows Defender SmartScreen Enabled"points = X [[check.passoverride]]type = "RegistryKeyNot"arg1 = "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\SmartScreenEnable"arg2 = "Off"[[check.passoverride]]type = "RegistryKey"arg1 = "HKLM\SOFTWARE\Policies\Microsoft\Windows\SystemEnableSmartScreen"arg2 = "1"[[check.passoverride]]type = "RegistryKey"arg1 = "HKLM\SOFTWARE\Policies\Microsoft\Windows\SystemEnableSmartScreen"arg2 = "2"—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
