### ISSUE TITLE
Rename Readme file

### ISSUE THREAD

**Issue by Mobmaker55** [sourque/aeacus#127]
Allow for ReadMe.conf to be also spelled as readme.conf or README.conf or whatever you please
(I'll add this feature in I just needed a reminder)

**Comment by Mobmaker55** [comment]
After looking through `go` documentation, without checking for every variation of the string "readme", is it possible for us to change readme to be all lower case like `scoring.conf`?

**Comment by sourque** [comment]
I'm not sure if there is a cross-platform case-insensitive file open feature. I think the best strategy would just be to check for those three most common formats (camel case, all lower, and all upper), and stop when we find one. That way we don't care if our file system is case sensitive.

**Comment by safinsingh** [comment]
This was addressed in #138 but there may now be issues when `aeacus` tries to remove the file during cleanup (e.g. https://github.com/elysium-suite/aeacus/blob/master/release_linux.go#L65). Opening a new issue for this.
