### ISSUE TITLE
Service will score as running even when stopped

### ISSUE THREAD

**Issue by hexadecimalDinosaur** [sourque/aeacus#130]
https://github.com/elysium-suite/aeacus/blob/faa157c527cac3d2fd282a86bdf0abac5e407ff7/cmd/checks_linux.go#L126

When a service is stopped `systemctl is-active` prints out `inactive` which still contains the word `active` causing the scoring engine to believe the service is still running

**Comment by safinsingh** [comment]
#129 resolves this, it will be merged as soon as it's reviewed
