### ISSUE TITLE
Nonfunctional on Windows 10 x64

### ISSUE THREAD

**Issue by GLippenholz** [sourque/aeacus#131]
I am just now finding this program and I have noticed it does not work on Windows 10 x64. Is there anyway to fix this or is there nothing i can do. I would also like to help with this project even though I have little coding knowledge, especially on making the gui version

**Comment by sourque** [comment]
Hey GLippenholz, thanks for reaching out! We're fairly confident it does work on Windows 10-- we would need more information to help you out and fix any possible issues. If you're new to reporting bugs, you may want to read [this page](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

As for the GUI version, we previously had a semi-working project on that, but decided it wasn't worth the effort when the CLI version worked well enough. It seemed that most GUI usage was only desirable when people were unfamiliar with CLI, and when they got used to it, the CLI version was easier/faster. But if you'd like to start a project working on that, or contribute any other features/code, anything is appreciated :)

**Comment by qb411** [comment]
I can confirm that it is working on Windows 10.  I have just prepped an image with this solution last night with the CLI.  It can be a bit complex though, so maybe Glippenholz isn't understanding/figuring out the full process.  I will say it was not straight forward from a high level when I started working with the solution, but once you have tested it a few times it starts to get much easier.

**Comment by Mobmaker55** [comment]
@GLippenholz Has your issue been resolved? If not, please provide more information and describe what your issues are with the software. 
This [Readme](https://github.com/elysium-suite/aeacus#readme) may be of assistance to you, it's a useful quickstart for how to use the software.

If you have solved your problem, feel free to close this issue! Thank you :)

**Comment by GLippenholz** [comment]
I believe the problem was the version of windows I was using. I will be trying it on a new vm to see if it works.
