### ISSUE TITLE
User Property Options

### ISSUE THREAD

**Issue by ShadowSchulme** [sourque/aeacus#133]
I dont see an option for User must change password at next logon on the [Windows User Properties page](https://github.com/elysium-suite/aeacus/blob/master/docs/userproperties.md) Is this a viable option? Also for User cannot change password? 

Thanks for your time,

**Comment by Mobmaker55** [comment]
Most Windows APIs do not currently have support for "User must change password at next logon", and therefore, we do not support that either.
As far as "User cannot change password", a new PR has been opened ( PR #135 ) to address this feature.
