### ISSUE TITLE
AutoCheckUpdatesEnabled check only works on certain distros

### ISSUE THREAD

**Issue by Mobmaker55** [sourque/aeacus#134]
I do not know what distros this check works on, but I know for a fact that it does not work on Debian 10. Personally, I feel this check should either be removed; however, the check could be massively reworked to look for the `APT::Periodic::Update-Package-Lists( |)"1";` in many places, instead of just the one file.

**Comment by Mobmaker55** [comment]
It's up to everyone as to how we deal with this issue

**Comment by sourque** [comment]
I don't think there has ever been a non-Debian based system produced in any CIAS competition, but I agree we should support other packaging systems. The simplest implementation is probably just a case statement in that function, like you suggested.

**Comment by Mobmaker55** [comment]
Debian still uses APT. the check only seems to work on Ubuntu distros, not Debian itself. That was the problem I was having. 
Considering that placement of that line is not consistent even within Ubuntu distros, let alone all APT-based distros, I feel like it's better just to deprecate the check so there is less bloat in the engine.
Having a 20 or 30 case switch statement would add a lot of useless functionality to the engine per image, considering most people stick to ubuntu anyway. 
Having people find the file and line and just make their own `FileContains` check is probably the better solution.

**Comment by safinsingh** [comment]
Didn't realize we were just checking one file; a `dirContainsRegex` in `/etc/apt/apt.conf.d/` should cover everything

**Comment by Mobmaker55** [comment]
I agree that will work for most APT-based systems. Although, with sour's statement of supporting other package systems, it depends.

As long as we stick to just APT-based distro support, then I agree that would probably be the best option.

**Comment by sourque** [comment]
Sorry that's my bad, I misread the initial issue. I also thought we were checking the config directory haha, so safinsingh's solution seem best. Reading more into other systems (dnf/pacman/etc), auto updates seem pretty unique/volatile-- so like you said, it's probably best if we didn't support them through this check.
