### ISSUE TITLE
Active Directory breaks UserRights check

### ISSUE THREAD

**Issue by Co1orguard** [sourque/aeacus#140]
After setting up Active Directory on a Windows Server 2019 instance it was found that the UserRights check would not work. Namely the checks on SeRemoteShutdownPrivilege and SeEnableDelegationPrivilege. My speculation is that group policy management is altered when changing to active directory. Here's the lines in the scoring.conf:

[[check]]
message = "Authenticated Users may not remotely shutdown the system"
points = 2
[[check.pass]]
type='UserRightsNot'
arg1='everyone'
arg2='SeEnableDelegationPrivilege'

[[check]]
message = "Everyone may not enable computer and user accounts to be trusted for delegation"
points = 2
[[check.pass]]
type='UserRightsNot'
arg1='everyone'
arg2='SeEnableDelegationPrivilege'

**Comment by Mobmaker55** [comment]
Just out of question, did you try "Everyone" with a capital E?

**Comment by Co1orguard** [comment]
> Just out of question, did you try "Everyone" with a capital E?

Yes. I have also tried changing the group that is being granted access

**Comment by Mobmaker55** [comment]
In powershell as admin, run 
`SecEdit.exe /export /cfg sec.cfg /log NUL;`
and see if the rights are in there.

**Comment by Co1orguard** [comment]
the output log is empty for that command
tried running without /log nul and still no output

changed value for both policies and the logs didn't change any
i.e. SeRemoteShutdownPrivilege, and SeEnableDelegationPrivilege

**Comment by Co1orguard** [comment]
I have attempted to monitor the status of SeRemoteShutdownPrivilege and SeEnableDelegationPrivilege to determine if they have been updated/changed. When doing so, the configuration file generated from the command you provided doesn't seem to update even after re-running it. Are there any other locations where a variable would affect "Force shutdown form a remote system" and "Enable computer and user accounts to be trusted for delegation". I have already looked through Microsoft Registry key documentation. Here's the link to the excel sheet with all the policies including those above: https://www.microsoft.com/en-us/download/details.aspx?id=25250. I have also looked through the sheet you've provided.   I have looked into using Get-GPRegistryValue, Get-GPOReport, and Get-GPO. Are there any other checks that would be able to monitor the status of these policies? I do not see any others in the documentation for the scoring engine. 

Thank you for any help that you can provide in getting these to score correctly.

**Comment by sourque** [comment]
I don't use Windows (so forgive my unfamiliarity), but it appears to be working for me. On a fresh DC, editing the group policy with `gpmc.msc` and then running `gpupdate /force`, the changes to `SeRemoteShutdownPrivilege` are reflected in the output of `secedit.exe` (which I honestly didn't expect to work haha).

Would you mind building `aeacus` from the in-progress 2.0 branch and seeing if that fixes your issue? Although, if you're not seeing the value updated in `sec.cfg` from the provided command, it may be a different issue. There's probably some way to cleanly score this with a registry check as well.

If you don't want to build yourself, I have the one I'm using [hosted here](https://host.sourque.com/aeacus-win32.zip) temporarily. The config I used:
```
[[check]]
message = "Authenticated users may not remotely shutdown the system"
points = 2
[[check.pass]]
type = 'UserRightsNot'
name = 'Everyone'
value = 'SeRemoteShutdownPrivilege'
```

**Comment by Co1orguard** [comment]
I ended up using this:

[[check]]
message = "Authenticated users may not shut down the system remotely"
points = 2
[[check.pass]]
type='FiileContainsNot'
arg1="C;\Windows\SYSVOL\domain\Policies\{insert super long policy}\MACHINE\Microsoft\WIndows NT\SecEdit\GptTmpl.inf'
arg2='SeRemoteShutdownPrivilege = *S-1-5-32-545'

tried tons of different solutions like the ones in this thread and none of them worked except checking SYSVOL

**Comment by sourque** [comment]
Bummer, sorry that we couldn't help you get it working as intended. It does seem to be working on my end, so I guess we'll chalk this up to the Curse of Windows. Insane workaround though, thanks for sending it!
