### ISSUE TITLE
Aeacus may not remove the README config file properly

### ISSUE THREAD

**Issue by safinsingh** [sourque/aeacus#143]
As of #138, the ReadMe.conf file can have the names `{readme,ReadMe,README}.conf`. This causes an issue during release because aeacus currently assumes that the file is named `ReadMe.conf` (see: https://github.com/elysium-suite/aeacus/blob/master/release_linux.go#L65).

**Comment by Mobmaker55** [comment]
As a secondary point, why is there so much being removed in `release_linux.go` ? A production build only needs to remove `misc/`, `LICENSE`, the `.conf` files, and `aeacus` itself ? 
(see: https://github.com/elysium-suite/aeacus/blob/master/release_linux.go#L66)

**Comment by sourque** [comment]
I think it's insurance against someone dropping using a dev build or full repo-- especially if someone wrote custom obfuscation/crypto stuff (and maybe checked it into git), we want to remove it on release.

**Comment by Mobmaker55** [comment]
Isn't that the end user's problem though? Also, it seems like bad practice to be *compiling* in `/opt/aeacus` in general...

**Comment by sourque** [comment]
Yeah, I suppose. But in the end, solving an end-user problem is what the project does :^) I figure if we can save somebody the trouble without making our code more complex or error-prone then it's worth it.
