### ISSUE TITLE
PermissionIs "Check type does not exist" on Windows

### ISSUE THREAD

**Issue by Pupstrr** [sourque/aeacus#153]
When using PermissionIs type on Windows, the check passes, but when scoring, it says that the type does not exist. 

`[FAIL] Check type does not exist: PermissionIs (reflect: call of reflect.Value.Call on zero Value)
`
```
config file:
	[[check.pass]]
	type = 'PermissionIsNot'
	path = 'C:\test'
	name = 'Everyone'
	value = "Write"
```

**Comment by sourque** [comment]
Sorry, I think it was `FilePermission` or something before b99b38380cb4d69f16c1e85f54a85094d983e3f1. We added a new release, let me know if that doesn't work.

**Comment by Pupstrr** [comment]
It works perfectly now!
