### ISSUE TITLE
ProgramVersion function does not work

### ISSUE THREAD

**Issue by jonathanxue5** [sourque/aeacus#154]
When using the ProgramVersion function on Ubuntu 20.04, I never get points even when the version is correct. It seems like a CommandOutput() error, but I'm not really sure.

**Comment by Mobmaker55** [comment]
Could you upload your specific check that you're using? along with your aeacus version (`sudo ./aeacus version`)

**Comment by jonathanxue5** [comment]
my check code is 
```
[[check]]
message = "Firefox has been updated"
points = 5
      [[check.pass]]
      type = "ProgramVersion"
      name = "firefox"
      value = "105.0+build2-0ubuntu0.20.04.1"
```
version is 2.0.3

**Comment by Mobmaker55** [comment]
Try this aeacus binary (just replace /opt/aeacus/aeacus with this version)
https://easyupload.io/f8y9qd
If it doesnt execute, then run `sudo chmod +x /opt/aeacus/aeacus`

**Comment by jonathanxue5** [comment]
Yes it works, thank you so much!

**Comment by Mobmaker55** [comment]
Awesome, thank you!
