### ISSUE TITLE
No desktop icons in Gnome anymore

### ISSUE THREAD

**Issue by tire-fire** [sourque/aeacus#158]
Since 2018 Gnome 3 has prevented desktop icons. https://gitlab.gnome.org/GNOME/nautilus/-/issues/158#problems-with-the-current-implementation

Is there a way to include a workaround with aeacus?

**Comment by Mobmaker55** [comment]
That would be out of scope of the scoring engine, considering we wish to support more than just GNOME-based systems anyway. 
Additionally, the process would likely have to change between systems, as Ubuntu (and most Ubuntu-based) systems have a desktop system, but "fresh" GNOME installs wouldn't. 
Have you tried looking at GNOME Extensions? There is a GNOME Extension to bring the Desktop back. 
https://extensions.gnome.org/extension/1465/desktop-icons/
