### ISSUE TITLE
Trying to set a check for a pathexistsnot (pls help)

### ISSUE THREAD

**Issue by Insane-Redditor** [sourque/aeacus#165]
[FAIL] Error decoding TOML: toml: line 190 (last key "check.passoverride.path"): invalid escape in string '\P'

**Comment by Insane-Redditor** [comment]
I'm trying to set a path C:\Program Files\File\File.exe, and it keeps getting stuck at \P

**Comment by sourque** [comment]
Hey, I'm guessing you're using double quotes to specify the path (like `path = "C:\Program Files\File\File.exe"`). When you use double quotes, TOML assumes you're trying to specify an escape sequence when it reads things like `\P` or `\F`.

You should use a string literal, by using single quotes. Or, you can escape your backslashes (like `C:\\Program Files\\File\\File.exe`). You can read more about it in the [TOML spec](https://toml.io/en/) or in our [check documentation](https://github.com/elysium-suite/aeacus/blob/master/docs/checks.md) (see the note under `DirContains`).

**Comment by Insane-Redditor** [comment]
> 

Ah.. I see what I've done wrong now. Thanks!
