### ISSUE TITLE
Windows Virus & Threat Protection

### ISSUE THREAD

**Issue by tyliec** [sourque/aeacus#169]
Enabling **Virus & Threat protection** on a Windows machine attacks the scoring system (deleting `phocus.exe`, and the related service)

I've observed this happening after running `aeacus.exe release`

<img width="493" alt="Screenshot 2023-07-21 at 9 54 55 PM" src="https://github.com/elysium-suite/aeacus/assets/15609358/8b83f690-9b8f-4ead-a46f-70b6fe281ddb">

**Comment by tyliec** [comment]
Workaround: 
<img width="569" alt="Screenshot 2023-07-21 at 10 25 26 PM" src="https://github.com/elysium-suite/aeacus/assets/15609358/40b878fe-0de0-4834-b6ff-30d2c233a828">

**Comment by sourque** [comment]
Thanks, that's funny... I guess, it is collecting a bunch of information about the machine. Also kind of an issue given that turning on threat protection could easily be a scored vulnerability. If you wanted to add a line to Tips and Tricks or somewhere on the README in a PR that would be appreciated. OR start removing stuff from the engine until it's not dumpstered by Windows, then we can see if we can work around that.

**Comment by Mobmaker55** [comment]
Are we just going to advise people to exclude (or maybe even have a release exclude thing if that's possible?) @sourque

**Comment by Akshay-Rohatgi** [comment]
We can probably just run `Add-MpPreference -ExclusionPath "C:\Aeacus\phocus.exe"` in the release function, right?

**Comment by Mobmaker55** [comment]
so we will have it run under the release Windows function and then just have a note that it "should automagically exclude itself"?

**Comment by Akshay-Rohatgi** [comment]
yeah I guess
