### ISSUE TITLE
.desktop files Firefox path

### ISSUE THREAD

**Issue by safinsingh** [sourque/aeacus#170]
https://github.com/elysium-suite/aeacus/blob/10b0ac8004c6e1637aec50786ed8910c0ef74414/misc/desktop/ScoringReport.desktop#L6

All `.desktop` files have an absolute path to Firefox, which can vary based on how it was installed (via Snap, etc.) We should instead just replace this with `firefox` or something else if a better solution exists.

**Comment by Mobmaker55** [comment]
Has anyone ever run into a problem with it? I don't disagree, but we should probably test it on all distros with Desktops (or the leading Desktop GNOME plugin for Fedora).

**Comment by safinsingh** [comment]
yes, someone in the cypat discord reported an issue with this after installing ffox as a snap

**Comment by Mobmaker55** [comment]
bumping this -- we had discussed that snap is just a different problem bc snap is sandboxed and won't access system files. Do we still want to do something for this, or are we thinking its okay bc what if someone poisons Firefox (side note, what if someone poisons Firefox?)
