### ISSUE TITLE
Desktop shortcuts are untrusted after release

### ISSUE THREAD

**Issue by tyliec** [sourque/aeacus#176]
After running `sudo ./aeceus release`, the automatically created desktop shortcuts are untrusted.

Machine specs

```
> uname -a
Linux bombe 6.2.0-32-generic #32~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 18 10:40:13 UTC 2 x86_64 x86_64 x_86_64 GNU/Linux
```

![Image](https://github.com/elysium-suite/aeacus/assets/15609358/d14ab2ad-ad82-48fc-b2f2-29979250eb73)

After Clicking to try and open

![Image](https://github.com/elysium-suite/aeacus/assets/15609358/2673f25e-53f9-4b06-a135-44d507f1f7fa)

**Comment by Mobmaker55** [comment]
We have tried different ways to trust it, but there is nothing that is compatible across all versions of Ubuntu. Especially considering we are trying to move to more DE's in the future, we are thinking about simply adding a disclaimer that states that you need to trust them yourself -- if you find a solution that works on Ubuntu 20, 22, Debian GNOME, and Fedora 36, then that would be highly appreciated!
