### ISSUE TITLE
./aeacus --verbose score doesn't create scoring report

### ISSUE THREAD

**Issue by frxyoz** [sourque/aeacus#179]
After creating the scoring config file and verifying the validity of the file through ./aeacus --verbose check, executing the command ./aeacus --verbose score scores the vulnerabilities and passes yet no scoring report is created inside the assets folder. Instead, this code is displayed. 
![image](https://github.com/elysium-suite/aeacus/assets/59369019/4eb995c2-7405-47a9-8971-36d595b69082)

**Comment by tyliec** [comment]
This looks like a configuration issue - mind posting the contents of your `scoring.conf`? @frxyoz
