### ISSUE TITLE
Manual phocus check

### ISSUE THREAD

**Issue by safinsingh** [sourque/aeacus#39]
Checking for the `INVOCATION_ID` env var stops systemd from running `phocus` on Ubuntu 16

https://github.com/sourque/aeacus/blob/40eaa1f7efafbee2f72667187c56f9f5ec779782/src/phocus_linux.go#L36-L40

![screenshot](https://media.discordapp.net/attachments/735615291857305641/739553045591097354/unknown.png)

**Comment by sourque** [comment]
Current solution is to not check if it's being run as a daemon, haha.
