### ISSUE TITLE
How to compile aeacus

### ISSUE THREAD

**Issue by Mobmaker55** [sourque/aeacus#96]
Following your directions, I tried to compile the latest version myself. I installed `go` and `garble` using the command `go get mvdan.cc/garble`. 
When running `make win`, I got this error:
`'make' is not recognized as an internal or external command,
operable program or batch file.`
What did I do wrong?

**Comment by safinsingh** [comment]
Assuming you're using Windows, you'll need to install GNU Make in order to build `aeacus` using something like [GNUWin](http://gnuwin32.sourceforge.net/), [MinGW](https://sourceforge.net/projects/mingw/), or [MSYS2](https://www.msys2.org/).

**Comment by Mobmaker55** [comment]
After trying multiple times to install GNUWin and MinGW (that part is probably on me), I switched to the latest version of Ubuntu (20.04.2).
I tried to run `make win` again, and this time, got this error:
`make: *** No rule to make target 'win'.  Stop.`
I also tried to just `make`. That did not work either.
I'm following your directions, I made sure to install go `go version go1.16 linux/amd64` and `garble` using `go get mvdan.cc/garble`.
What am I still missing?

**Comment by safinsingh** [comment]
Ah, my bad; we had removed the Makefile in an earlier commit. As of c08b24029d6684bf393b7bd0352dfe80c1dee96e, you should be able to run the command successfully. Please re-pull and try again; sorry about that.

**Comment by Mobmaker55** [comment]
It's alright, I'm not used to compiling with anything other than `gradle` or `Maven`, so this is a good new experience for me, haha!
Okay, so I think I messed up installing garble... 
`mob@ubuntu:~/aeacus$ make win`
`CGO_ENABLED=0 GOOS=windows garble build -ldflags '-s -w' -tags phocus -o ./phocus.exe . && \`
`CGO_ENABLED=0 GOOS=windows garble build -ldflags '-s -w' -o ./aeacus.exe . && \`
`echo "Windows production build successful!"`
`/bin/sh: 1: garble: not found`
`make: *** [Makefile:30: win] Error 127`
That's the invocation and the error? that resulted.

**Comment by safinsingh** [comment]
Is `garble` installed and has it been added to your `$PATH`?

**Comment by Mobmaker55** [comment]
I installed `garble` using the command `go get mvdan.cc/garble`
but other than that, I haven't done anything else...

**Comment by Mobmaker55** [comment]
I don't see where `garble` would be installed, and I can't find it just browsing through my file tree. How would I add it to my `$PATH`?

**Comment by safinsingh** [comment]
By default, Go installs binaries to `$GOPATH/bin`. In order to set your `$PATH` correctly, execute the following:

```sh
export PATH="$PATH:${GOPATH:-$HOME/go}/bin"
```

**Comment by Mobmaker55** [comment]
This is the error I received after running your export PATH- 
It started for like 10 minutes, and then randomly stopped with this error, I tried it again just to be sure, but this was the same error the second time too.

> go list error: exit status 1: ../go/pkg/mod/github.com/gen2brain/beeep@v0.0.0-20200526185328-e9c15c258e28/notify_windows.go:16:2: missing go.sum entry for module providing package golang.org/x/sys/windows/registry (imported by github.com/elysium-suite/aeacus/cmd); to add:
	go get github.com/elysium-suite/aeacus/cmd
../go/pkg/mod/github.com/iamacarpet/go-win64api@v0.0.0-20200715182619-8cbc936e1a5a/services.go:12:2: missing go.sum entry for module providing package golang.org/x/sys/windows (imported by github.com/elysium-suite/aeacus/cmd); to add:
	go get github.com/elysium-suite/aeacus/cmd
../go/pkg/mod/github.com/iamacarpet/go-win64api@v0.0.0-20200715182619-8cbc936e1a5a/services.go:13:2: missing go.sum entry for module providing package golang.org/x/sys/windows/svc (imported by github.com/judwhite/go-svc/svc); to add:
	go get github.com/judwhite/go-svc/svc@v1.1.2
../go/pkg/mod/github.com/iamacarpet/go-win64api@v0.0.0-20200715182619-8cbc936e1a5a/services.go:14:2: missing go.sum entry for module providing package golang.org/x/sys/windows/svc/mgr (imported by github.com/iamacarpet/go-win64api); to add:
	go get github.com/iamacarpet/go-win64api@v0.0.0-20200715182619-8cbc936e1a5a
go build golang.org/x/sys/windows/registry: no Go files in 
go build golang.org/x/sys/windows: no Go files in 
go build golang.org/x/sys/windows/svc: no Go files in 
go build golang.org/x/sys/windows/svc/mgr: no Go files in 
make: *** [Makefile:30: win] Error 1

**Comment by Mobmaker55** [comment]
I kept trying different stuff (including re-cloning the source), but nothing has worked. I have no idea how to fix this error, do you have any ideas?

**Comment by safinsingh** [comment]
Have you installed dependencies with `go get -v -d -t ./...`?

**Comment by sourque** [comment]
If your goal is to just have the code compiled, and you're not looking to change `crypto.go` at all, we also made a 'new' release which should be up to date.

**Comment by Mobmaker55** [comment]
> Have you installed dependencies with `go get -v -d -t ./...`?

Thank you :) this worked! Sorry, I've never used `go` before, this is all new to me.
However, I did change `crypto.go` a little, so I want to compile that in. 

Okay, so now, do I just move `aeacus.exe` and `phocus.exe` to my `C:\aeacus` directory? Or do I need to move more stuff?

**Comment by safinsingh** [comment]
You'll also need the `assets` and `misc` directories from the repository; that's all.

**Comment by Mobmaker55** [comment]
> You'll also need the `assets` and `misc` directories from the repository; that's all.

The `misc` directory is not in your [latest release](https://github.com/elysium-suite/aeacus/releases/tag/v1.6.3)... would I need to download and install the `misc` directory separately from a release? 

I'm trying to make a configuration guide not only for myself, but for my team, so they can understand how to use aeacus. So, I'm sorry if this is a lot of questions-

**Comment by safinsingh** [comment]
No problem. The Makefile hasn't been updated to include the `misc` directory but you should copy it from the cloned repository into `/opt/aeacus`.

**Comment by Mobmaker55** [comment]
Sounds good! This answers all of my compilation questions, thank you!

**Comment by Mobmaker55** [comment]
I feel bad about bothering all of you more, but I'm once again trying with Windows (I am so sorry)...
I ran `make win`, and got a different error that I've never seen before-

>  C:\(directory stuff)>`make win`
`CGO_ENABLED=0 GOOS=windows garble build -ldflags '-s -w' -tags phocus -o ./phocus.exe . && \`
`CGO_ENABLED=0 GOOS=windows garble build -ldflags '-s -w' -o ./aeacus.exe . && \`
`echo "Windows production build successful!"`
`'CGO_ENABLED' is not recognized as an internal or external command,`
`operable program or batch file.`
`make: *** [Makefile:30: win] Error 1`

It's probably something stupid and easy to fix, but I have no idea how to fix this...
again, my first time using Go, so I have no idea what I'm doing even remotely haha

Thank you so much for taking the time to respond to all of my questions too, it's really helpful and kind of all of you!

EDIT: I'm just going to save all of you time and go back to compiling on the FAR SUPERIOR Linux. Sorry for spamming your inboxes by opening and closing this issue haha...

**Comment by safinsingh** [comment]
No worries! The reason it wasn't working is because there's a different syntax for setting environment variables on `cmd`; namely `set`/`setx`. I would agree, however, that it's much easier to compile on Linux 😄

**Comment by Mobmaker55** [comment]
> No worries! The reason it wasn't working is because there's a different syntax for setting environment variables on `cmd`; namely `set`/`setx`. I would agree, however, that it's much easier to compile on Linux 😄

Right! I didn't realize that's how a Makefile worked-- shows how much I know xD
I'll totally try that on Windows some other time... whenever that is :P
